version: '3'
services:
  app:
    container_name: "nginx-proxy-manager"
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:

# Internal
# 10.10.2.252/24
      - ${Inetrnal_IP}:80:80/tcp
      - ${Inetrnal_IP}:443:443/tcp
      - ${Inetrnal_IP}:${Inetrnal_management_PORT}:81/tcp

# External
#10.20.0.252/24
      - ${External_IP}:80:80/tcp
      - ${External_IP}:443:443/tcp

    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - ${DATA_PATH}/letsencrypt.ini:/etc/letsencrypt.ini
      - ${DATA_PATH}/data:/data
      - ${DATA_PATH}/letsencrypt:/etc/letsencrypt

    environment:
      DISABLE_IPV6: 'true'
