version: '3'
services:
  app:
    container_name: "nginx-proxy-manager"
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
# 10.20.0.252/24
      - '10.20.0.252:80:80/tcp'
      - '10.20.0.252:443:443/tcp'
# 10.10.2.252/24
      - '10.10.2.252:80:80/tcp'
      - '10.10.2.252:443:443/tcp'
      - '10.10.2.252:81:81/tcp'

    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - ${DATA_PATH}/data:/data
      - ${DATA_PATH}/letsencrypt:/etc/letsencrypt
      - ${DATA_PATH}/letsencrypt.ini:/etc/letsencrypt.ini

    environment:
      DISABLE_IPV6: 'true'
